#pragma once

// "AI in a jar" mascot frames for the voice screen, generated by
// tools/gen_mascot.py (which draws them and runs LVGL's own LVGLImage.py, so the
// descriptors always match this LVGL version). 96x96 RGB565A8, ~27 KB each.
//
// Frames are selected by state, and while recording by capture level, so the
// picture answers "is it hearing me?" — the device's only local proof that audio
// is really being captured.
#include "lvgl.h"

LV_IMAGE_DECLARE(backdrop);         // ink-wash landscape, tools/gen_backdrop.py

LV_IMAGE_DECLARE(mascot_waiting);   // waiting for the PC to connect
LV_IMAGE_DECLARE(mascot_idle);      // connected, ready
LV_IMAGE_DECLARE(mascot_quiet);     // recording, level 0-33
LV_IMAGE_DECLARE(mascot_loud);      // recording, level 34-66
LV_IMAGE_DECLARE(mascot_peak);      // recording, level 67-100
LV_IMAGE_DECLARE(mascot_fault);     // bluetooth or audio unavailable
